describe ('My First Test', () => {
it('Test Website', () => {
  cy.visit('https://opensource-demo.orangehrmlive.com/')    
  cy.url('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')    
  cy.title().should('eq', "OrangeHRM")
  cy.get('.orangehrm-login-branding > img')
    .should('be.visible')
  cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input')
  .should('be.visible')
  cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input')
    .should('be.visible')
  cy.contains('Password').should('contain', 'Password')
  cy.get('.oxd-button')
    .should('be.visible')
    .should('contain', 'Login')

  })
it('Should not login with invalid credentials', () => {
  cy.visit('https://opensource-demo.orangehrmlive.com/')
  cy.get('input[name="username"]').type('wronguser')
  cy.get('input[name="password"]').type('wrongpass')
  cy.get('button[type="submit"]').click()
  cy.get('.oxd-alert-content-text').should('contain.text', 'Invalid credentials')
})
})